resolver: lts-14.27

packages:
- funflow
- funflow-aws
- funflow-checkpoints
- funflow-jobs
- funflow-examples
- funflow-cwl

extra-deps:
- aws-0.20
- hedis-0.12.5@sha256:5e3f47b935a48e57c44197f715a26d88a33c46c045a8c19d75b0d7ebc4ae3cbe

nix:
  packages:
  - zlib
