resolver: lts-15.14

packages:
- cas/hashable
- cas/s3
- cas/store
- funflow
- funflow-aws
- funflow-checkpoints
- funflow-jobs
- funflow-examples
- funflow-cwl

extra-deps:
- aws-0.22
- sqlite-simple-0.4.18.0
- store-0.7.4
- direct-sqlite-2.3.26
- store-core-0.4.4.2
- th-utilities-0.2.4.0

nix:
  packages:
  - zlib
