version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:2.0
    steps:
      - checkout
      - run:
          name: Setup Cachix
          command: |
            apk --no-progress update
            apk --no-progress add ca-certificates
            nix-channel --update
            # Install cachix and activate project cache
            nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/1d4de0d552ae9aa66a5b8dee5fb0650a4372d148
            USER=dummy cachix use tweag
      - run:
          name: Building
          command: nix-store --query --requisites --include-outputs $(nix-instantiate nix/ci.nix -A required-packages) | cachix push tweag
      - run:
          name: Running tests
          command: nix-build nix/ci.nix -A required-tests | cachix push tweag
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
